// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PrefHandler is an autogenerated mock type for the PrefHandler type
type PrefHandler struct {
	mock.Mock
}

type PrefHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *PrefHandler) EXPECT() *PrefHandler_Expecter {
	return &PrefHandler_Expecter{mock: &_m.Mock}
}

// GetBool provides a mock function with given fields: _a0
func (_m *PrefHandler) GetBool(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PrefHandler_GetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBool'
type PrefHandler_GetBool_Call struct {
	*mock.Call
}

// GetBool is a helper method to define mock.On call
//   - _a0 string
func (_e *PrefHandler_Expecter) GetBool(_a0 interface{}) *PrefHandler_GetBool_Call {
	return &PrefHandler_GetBool_Call{Call: _e.mock.On("GetBool", _a0)}
}

func (_c *PrefHandler_GetBool_Call) Run(run func(_a0 string)) *PrefHandler_GetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PrefHandler_GetBool_Call) Return(_a0 bool) *PrefHandler_GetBool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PrefHandler_GetBool_Call) RunAndReturn(run func(string) bool) *PrefHandler_GetBool_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function with given fields: _a0
func (_m *PrefHandler) GetString(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PrefHandler_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type PrefHandler_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - _a0 string
func (_e *PrefHandler_Expecter) GetString(_a0 interface{}) *PrefHandler_GetString_Call {
	return &PrefHandler_GetString_Call{Call: _e.mock.On("GetString", _a0)}
}

func (_c *PrefHandler_GetString_Call) Run(run func(_a0 string)) *PrefHandler_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PrefHandler_GetString_Call) Return(_a0 string) *PrefHandler_GetString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PrefHandler_GetString_Call) RunAndReturn(run func(string) string) *PrefHandler_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// SetBool provides a mock function with given fields: _a0, _a1
func (_m *PrefHandler) SetBool(_a0 string, _a1 bool) {
	_m.Called(_a0, _a1)
}

// PrefHandler_SetBool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBool'
type PrefHandler_SetBool_Call struct {
	*mock.Call
}

// SetBool is a helper method to define mock.On call
//   - _a0 string
//   - _a1 bool
func (_e *PrefHandler_Expecter) SetBool(_a0 interface{}, _a1 interface{}) *PrefHandler_SetBool_Call {
	return &PrefHandler_SetBool_Call{Call: _e.mock.On("SetBool", _a0, _a1)}
}

func (_c *PrefHandler_SetBool_Call) Run(run func(_a0 string, _a1 bool)) *PrefHandler_SetBool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *PrefHandler_SetBool_Call) Return() *PrefHandler_SetBool_Call {
	_c.Call.Return()
	return _c
}

func (_c *PrefHandler_SetBool_Call) RunAndReturn(run func(string, bool)) *PrefHandler_SetBool_Call {
	_c.Call.Return(run)
	return _c
}

// SetString provides a mock function with given fields: _a0, _a1
func (_m *PrefHandler) SetString(_a0 string, _a1 string) {
	_m.Called(_a0, _a1)
}

// PrefHandler_SetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetString'
type PrefHandler_SetString_Call struct {
	*mock.Call
}

// SetString is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *PrefHandler_Expecter) SetString(_a0 interface{}, _a1 interface{}) *PrefHandler_SetString_Call {
	return &PrefHandler_SetString_Call{Call: _e.mock.On("SetString", _a0, _a1)}
}

func (_c *PrefHandler_SetString_Call) Run(run func(_a0 string, _a1 string)) *PrefHandler_SetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PrefHandler_SetString_Call) Return() *PrefHandler_SetString_Call {
	_c.Call.Return()
	return _c
}

func (_c *PrefHandler_SetString_Call) RunAndReturn(run func(string, string)) *PrefHandler_SetString_Call {
	_c.Call.Return(run)
	return _c
}

// NewPrefHandler creates a new instance of PrefHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrefHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrefHandler {
	mock := &PrefHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
